/**
 * Timer ownership contracts shared by runtime startup and generated bytecode.
 *
 * <p>{@link com.ll.metrics.latency.timer.Timers#snapshots()} is the application-facing reporting
 * API. {@link com.ll.metrics.latency.timer.Timers#claim(String)} and
 * {@link com.ll.metrics.latency.timer.Timer} are public for generated bytecode linkage and are
 * instrumentation SPI, not a general programmatic timing API.
 */
package com.ll.metrics.latency.timer;
