package com.ll.metrics.latency.timer;

import com.ll.metrics.latency.snapshot.LatencySnapshot;

/**
 * Mutable recording contract used by generated instrumentation.
 *
 * <p>This type is public so generated bytecode can link to it, but it is an instrumentation SPI,
 * not a general application timing API. Application code should read immutable {@code
 * TimerSnapshot} values through {@link Timers#snapshots()} instead of recording directly.
 *
 * <p>Each timer is owned by exactly one generated method identity and records only complete
 * successful executions of that {@code @Timed} method. Duration values are nanoseconds.
 */
public interface Timer {
  /**
   * Records one successful method execution duration.
   *
   * @param durationNanos elapsed duration in nanoseconds
   * @throws IllegalArgumentException when {@code durationNanos} is negative
   */
  void record(long durationNanos);

  /**
   * Returns an immutable point-in-time summary of this timer.
   *
   * @return snapshot with latency values in nanoseconds
   */
  LatencySnapshot snapshot();
}
