/**
 * Constants shared by generated bytecode, runtime startup, and the Maven plugin.
 *
 * <p>This package is public for cross-module linkage but should be treated as instrumentation SPI.
 */
package com.ll.metrics.latency.constants;
